// <auto-generated />
using System;
using System.Collections.Generic;
using Investimentos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Investimentos.Infrastructure.Migrations
{
    [DbContext(typeof(InvestimentosDbContext))]
    [Migration("20260904202412_AdicionarInvestidor")]
    partial class AdicionarInvestidor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Investimentos.Domain.Entities.Ativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TipoAtivoId")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Ticker", "Investimentos.Domain.Entities.Ativo.Ticker#Ticker", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Ticker");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TipoAtivoId");

                    b.ToTable("Ativo", (string)null);
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.ClasseAtivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("ClasseAtivo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Codigo = "RENDA_FIXA",
                            Nome = "Renda Fixa"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Codigo = "RENDA_VARIAVEL",
                            Nome = "Renda Variável"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Codigo = "FUNDOS",
                            Nome = "Fundos"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Codigo = "ALTERNATIVOS",
                            Nome = "Alternativos"
                        });
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.Investidor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Investidor", (string)null);
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.TipoAtivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("ClasseAtivoId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClasseAtivoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TipoAtivo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            ClasseAtivoId = 2,
                            Codigo = "ACAO",
                            Nome = "Ação"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            ClasseAtivoId = 3,
                            Codigo = "FII",
                            Nome = "Fundo Imobiliário"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            ClasseAtivoId = 3,
                            Codigo = "ETF",
                            Nome = "ETF"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            ClasseAtivoId = 2,
                            Codigo = "BDR",
                            Nome = "BDR"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            ClasseAtivoId = 1,
                            Codigo = "TESOURO_DIRETO",
                            Nome = "Tesouro Direto"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            ClasseAtivoId = 1,
                            Codigo = "CDB",
                            Nome = "CDB"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            ClasseAtivoId = 1,
                            Codigo = "LCI",
                            Nome = "LCI"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            ClasseAtivoId = 1,
                            Codigo = "LCA",
                            Nome = "LCA"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            ClasseAtivoId = 1,
                            Codigo = "DEBENTURE",
                            Nome = "Debênture"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            ClasseAtivoId = 1,
                            Codigo = "POUPANCA",
                            Nome = "Poupança"
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            ClasseAtivoId = 3,
                            Codigo = "FUNDO_RENDA_FIXA",
                            Nome = "Fundo de Renda Fixa"
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            ClasseAtivoId = 3,
                            Codigo = "FUNDO_ACOES",
                            Nome = "Fundo de Ações"
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            ClasseAtivoId = 3,
                            Codigo = "FUNDO_MULTIMERCADO",
                            Nome = "Fundo Multimercado"
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            ClasseAtivoId = 3,
                            Codigo = "FUNDO_CAMBIAL",
                            Nome = "Fundo Cambial"
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            ClasseAtivoId = 4,
                            Codigo = "CRIPTOMOEDA",
                            Nome = "Criptomoeda"
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            ClasseAtivoId = 4,
                            Codigo = "CAMBIO",
                            Nome = "Câmbio"
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            ClasseAtivoId = 4,
                            Codigo = "COMMODITY",
                            Nome = "Commodity"
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            ClasseAtivoId = 4,
                            Codigo = "OURO",
                            Nome = "Ouro"
                        });
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.Ativo", b =>
                {
                    b.HasOne("Investimentos.Domain.Entities.TipoAtivo", "TipoAtivo")
                        .WithMany()
                        .HasForeignKey("TipoAtivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoAtivo");
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.TipoAtivo", b =>
                {
                    b.HasOne("Investimentos.Domain.Entities.ClasseAtivo", "ClasseAtivo")
                        .WithMany()
                        .HasForeignKey("ClasseAtivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClasseAtivo");
                });
#pragma warning restore 612, 618
        }
    }
}
