// <auto-generated />
using Investimentos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Investimentos.Infrastructure.Migrations
{
    [DbContext(typeof(InvestimentosDbContext))]
    [Migration("20260919160000_AdicionarValorPatrimonialAtivo")]
    partial class AdicionarValorPatrimonialAtivo
    {
        protected override void BuildTargetModel(
            ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(
                modelBuilder);

            modelBuilder.Entity(
                "Investimentos.Domain.Entities.ValorPatrimonialAtivo",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex(
                            "AtivoId",
                            "DataReferencia")
                        .IsUnique();

                    b.ToTable(
                        "ValorPatrimonialAtivo",
                        (string)null);
                });

            modelBuilder.Entity(
                "Investimentos.Domain.Entities.ValorPatrimonialAtivo",
                b =>
                {
                    b.HasOne(
                            "Investimentos.Domain.Entities.Ativo",
                            "Ativo")
                        .WithMany()
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ativo");
                });
#pragma warning restore 612, 618
        }
    }
}
