// <auto-generated />
using Investimentos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Investimentos.Infrastructure.Migrations
{
    [DbContext(typeof(InvestimentosDbContext))]
    [Migration("20260919160000_AdicionarValorPatrimonialAtivo")]
    partial class AdicionarValorPatrimonialAtivo
    {
        protected override void BuildTargetModel(
            ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            new InvestimentosDbContextModelSnapshot()
                .BuildModel(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
