// <auto-generated />
using System;
using Investimentos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Investimentos.Infrastructure.Migrations
{
    [DbContext(typeof(InvestimentosDbContext))]
    partial class InvestimentosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Investimentos.Domain.Entities.Ativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Ticker");

                    b.Property<int>("TipoAtivoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.HasIndex("TipoAtivoId");

                    b.ToTable("Ativo", (string)null);
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.ClasseAtivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("ClasseAtivo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Codigo = "RENDA_FIXA",
                            Nome = "Renda Fixa"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Codigo = "RENDA_VARIAVEL",
                            Nome = "Renda Variável"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Codigo = "FUNDOS",
                            Nome = "Fundos"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Codigo = "ALTERNATIVOS",
                            Nome = "Alternativos"
                        });
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.CotacaoAtivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvestidorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId", "DataReferencia")
                        .IsUnique();

                    b.ToTable("CotacaoAtivo", (string)null);
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.DescontoFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DataPagamento", "Tipo");

                    b.ToTable("DescontoFiscal", (string)null);
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.HistoricoPatrimonio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvestidorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorCarteira")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvestidorId", "DataReferencia")
                        .IsUnique();

                    b.ToTable("HistoricoPatrimonio", (string)null);
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.Investidor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Investidor", (string)null);
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.Operacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvestidorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("Sequencia")
                        .HasColumnType("int");

                    b.Property<decimal>("Taxas")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoOperacaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.HasIndex("TipoOperacaoId");

                    b.HasIndex("InvestidorId", "Data", "Sequencia")
                        .IsUnique();

                    b.ToTable("Operacao", (string)null);
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.OperacaoOpcao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Contratos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvestidorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Natureza")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("PrecoRecompraUnitario")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("PremioUnitario")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("ResultadoInformado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Strike")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Taxas")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TickerOpcao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoOpcao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("ValorExecucao")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.HasIndex("TickerOpcao");

                    b.HasIndex("InvestidorId", "DataOperacao");

                    b.ToTable("OperacaoOpcao", (string)null);
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.Provento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataCom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("InvestidorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QuantidadeBase")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("ValorPorUnidade")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("ValorRecebido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.HasIndex("InvestidorId", "DataPagamento");

                    b.ToTable("Provento", (string)null);
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.SaldoDisponivel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvestidorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvestidorId", "DataReferencia")
                        .IsUnique();

                    b.ToTable("SaldoDisponivel", (string)null);
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.ValorPatrimonialAtivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvestidorId");

                    b.HasIndex("AtivoId", "InvestidorId", "DataReferencia")
                        .IsUnique();

                    b.ToTable("ValorPatrimonialAtivo", (string)null);
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.TipoAtivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("ClasseAtivoId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClasseAtivoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TipoAtivo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            ClasseAtivoId = 2,
                            Codigo = "ACAO",
                            Nome = "Ação"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            ClasseAtivoId = 3,
                            Codigo = "FII",
                            Nome = "Fundo Imobiliário"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            ClasseAtivoId = 3,
                            Codigo = "ETF",
                            Nome = "ETF"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            ClasseAtivoId = 2,
                            Codigo = "BDR",
                            Nome = "BDR"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            ClasseAtivoId = 1,
                            Codigo = "TESOURO_DIRETO",
                            Nome = "Tesouro Direto"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            ClasseAtivoId = 1,
                            Codigo = "CDB",
                            Nome = "CDB"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            ClasseAtivoId = 1,
                            Codigo = "LCI",
                            Nome = "LCI"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            ClasseAtivoId = 1,
                            Codigo = "LCA",
                            Nome = "LCA"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            ClasseAtivoId = 1,
                            Codigo = "DEBENTURE",
                            Nome = "Debênture"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            ClasseAtivoId = 1,
                            Codigo = "POUPANCA",
                            Nome = "Poupança"
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            ClasseAtivoId = 3,
                            Codigo = "FUNDO_RENDA_FIXA",
                            Nome = "Fundo de Renda Fixa"
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            ClasseAtivoId = 3,
                            Codigo = "FUNDO_ACOES",
                            Nome = "Fundo de Ações"
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            ClasseAtivoId = 3,
                            Codigo = "FUNDO_MULTIMERCADO",
                            Nome = "Fundo Multimercado"
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            ClasseAtivoId = 3,
                            Codigo = "FUNDO_CAMBIAL",
                            Nome = "Fundo Cambial"
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            ClasseAtivoId = 4,
                            Codigo = "CRIPTOMOEDA",
                            Nome = "Criptomoeda"
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            ClasseAtivoId = 4,
                            Codigo = "CAMBIO",
                            Nome = "Câmbio"
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            ClasseAtivoId = 4,
                            Codigo = "COMMODITY",
                            Nome = "Commodity"
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            ClasseAtivoId = 4,
                            Codigo = "OURO",
                            Nome = "Ouro"
                        });
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.TipoOperacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TipoOperacao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Codigo = "COMPRA",
                            Nome = "Compra"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Codigo = "VENDA",
                            Nome = "Venda"
                        });
                });

            modelBuilder.Entity("Investimentos.Domain.Usuarios.TokenRecuperacaoSenha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUtilizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "DataExpiracao");

                    b.ToTable("TokenRecuperacaoSenha", (string)null);
                });

            modelBuilder.Entity("Investimentos.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AprovadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AprovadoPorUsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Investimentos.Domain.Usuarios.UsuarioInvestidor", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvestidorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioId", "InvestidorId");

                    b.HasIndex("InvestidorId");

                    b.ToTable("UsuarioInvestidor", (string)null);
                });

            modelBuilder.Entity("Investimentos.Domain.Usuarios.UsuarioInvestidorPermissao", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvestidorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Permissao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioId", "InvestidorId", "Permissao");

                    b.HasIndex("InvestidorId");

                    b.ToTable("UsuarioInvestidorPermissao", (string)null);
                });

            modelBuilder.Entity("Investimentos.Domain.Usuarios.UsuarioPermissao", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Permissao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioId", "Permissao");

                    b.ToTable("UsuarioPermissao", (string)null);
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.Ativo", b =>
                {
                    b.HasOne("Investimentos.Domain.Entities.TipoAtivo", "TipoAtivo")
                        .WithMany()
                        .HasForeignKey("TipoAtivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoAtivo");
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.CotacaoAtivo", b =>
                {
                    b.HasOne("Investimentos.Domain.Entities.Ativo", "Ativo")
                        .WithMany()
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ativo");
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.HistoricoPatrimonio", b =>
                {
                    b.HasOne("Investimentos.Domain.Entities.Investidor", "Investidor")
                        .WithMany()
                        .HasForeignKey("InvestidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Investidor");
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.Operacao", b =>
                {
                    b.HasOne("Investimentos.Domain.Entities.Ativo", "Ativo")
                        .WithMany()
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Investimentos.Domain.Entities.Investidor", "Investidor")
                        .WithMany()
                        .HasForeignKey("InvestidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Investimentos.Domain.Entities.TipoOperacao", "TipoOperacao")
                        .WithMany()
                        .HasForeignKey("TipoOperacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ativo");

                    b.Navigation("Investidor");

                    b.Navigation("TipoOperacao");
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.OperacaoOpcao", b =>
                {
                    b.HasOne("Investimentos.Domain.Entities.Ativo", "Ativo")
                        .WithMany()
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Investimentos.Domain.Entities.Investidor", "Investidor")
                        .WithMany()
                        .HasForeignKey("InvestidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ativo");

                    b.Navigation("Investidor");
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.Provento", b =>
                {
                    b.HasOne("Investimentos.Domain.Entities.Ativo", "Ativo")
                        .WithMany()
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Investimentos.Domain.Entities.Investidor", "Investidor")
                        .WithMany()
                        .HasForeignKey("InvestidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ativo");

                    b.Navigation("Investidor");
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.SaldoDisponivel", b =>
                {
                    b.HasOne("Investimentos.Domain.Entities.Investidor", "Investidor")
                        .WithMany()
                        .HasForeignKey("InvestidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Investidor");
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.ValorPatrimonialAtivo", b =>
                {
                    b.HasOne("Investimentos.Domain.Entities.Ativo", "Ativo")
                        .WithMany()
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Investimentos.Domain.Entities.Investidor", "Investidor")
                        .WithMany()
                        .HasForeignKey("InvestidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ativo");

                    b.Navigation("Investidor");
                });

            modelBuilder.Entity("Investimentos.Domain.Entities.TipoAtivo", b =>
                {
                    b.HasOne("Investimentos.Domain.Entities.ClasseAtivo", "ClasseAtivo")
                        .WithMany()
                        .HasForeignKey("ClasseAtivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClasseAtivo");
                });

            modelBuilder.Entity("Investimentos.Domain.Usuarios.TokenRecuperacaoSenha", b =>
                {
                    b.HasOne("Investimentos.Domain.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Investimentos.Domain.Usuarios.Usuario", b =>
                {
                    b.HasOne("Investimentos.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AprovadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Investimentos.Domain.Usuarios.UsuarioInvestidor", b =>
                {
                    b.HasOne("Investimentos.Domain.Entities.Investidor", "Investidor")
                        .WithMany()
                        .HasForeignKey("InvestidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Investimentos.Domain.Usuarios.Usuario", "Usuario")
                        .WithMany("Investidores")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investidor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Investimentos.Domain.Usuarios.UsuarioInvestidorPermissao", b =>
                {
                    b.HasOne("Investimentos.Domain.Entities.Investidor", null)
                        .WithMany()
                        .HasForeignKey("InvestidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Investimentos.Domain.Usuarios.Usuario", "Usuario")
                        .WithMany("InvestidoresPermissoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Investimentos.Domain.Usuarios.UsuarioPermissao", b =>
                {
                    b.HasOne("Investimentos.Domain.Usuarios.Usuario", "Usuario")
                        .WithMany("Permissoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Investimentos.Domain.Usuarios.Usuario", b =>
                {
                    b.Navigation("Investidores");

                    b.Navigation("InvestidoresPermissoes");

                    b.Navigation("Permissoes");
                });
#pragma warning restore 612, 618
        }
    }
}
