FROM node:24-alpine AS build
WORKDIR /app

COPY frontend/investimentos-web/package*.json ./
RUN npm ci

COPY frontend/investimentos-web/ ./
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY frontend/investimentos-web/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
